export const topTechCompanies = [
    "Apple",
    "Microsoft",
    "Nvidia",
    "TikTok",
    "Alphabet",
    "Amazon",
    "Meta",
    "Taiwan Semiconductor Manufacturing Company (TSMC)",
    "Broadcom",
    "Tesla",
    "Tencent",
    "Samsung Electronics",
    "ASML",
    "Google",
    "Oracle",
    "Adobe",
    "Salesforce",
    "Cisco",
    "IBM",
    "Intel",
    "Shopify",
    "SAP",
    "Accenture",
    "Qualcomm",
    "AMD",
    "ServiceNow",
    "Intuit",
    "Snowflake",
    "Workday",
    "Square",
    "Spotify",
    "Zoom",
    "Palantir",
    "Dropbox",
    "Atlassian",
    "Twilio",
    "Datadog",
    "CrowdStrike",
    "Okta",
    "Zscaler",
    "DocuSign",
    "RingCentral",
    "Slack Technologies",
    "Pinterest",
    "Snap",
    "Uber",
    "Lyft",
    "Airbnb",
    "DoorDash",
    "Robinhood",
    "Coinbase",
    "Stripe",
    "SpaceX",
    "Epic Games",
    "ByteDance",
    "Didi Chuxing",
    "Xiaomi",
    "Meituan",
    "JD.com",
    "Baidu",
    "Alibaba",
    "Huawei",
    "Sony",
    "LG Electronics",
    "Panasonic",
    "Toshiba",
    "Fujitsu",
    "NEC Corporation",
    "Hitachi",
    "Nokia",
    "Ericsson",
    "Siemens",
    "Philips",
    "SAP",
    "Capgemini",
    "Infosys",
    "Wipro",
    "Tata Consultancy Services",
    "HCL Technologies",
    "Tech Mahindra",
    "Cognizant",
    "DXC Technology",
    "HP",
    "Dell Technologies",
    "Lenovo",
    "Acer",
    "Asus",
    "Micron Technology",
    "Western Digital",
    "Seagate Technology",
    "NetApp",
    "VMware",
    "Red Hat",
    "Citrix Systems",
    "Fortinet",
    "Palo Alto Networks",
    "Check Point Software",
    "Trend Micro",
    "Kaspersky Lab",
    "McAfee",
    "Symantec",
    "NortonLifeLock",
  ];